"""
prompt_builder.py

Creates prompts for the LLM based on traffic analysis.
"""


def build_traffic_prompt(report, location="Unknown Location"):
    """
    Build a structured prompt for the LLM.

    Parameters
    ----------
    report : dict
        Traffic report generated by report_generator.py

    location : str
        Location of the traffic video

    Returns
    -------
    str
        Prompt for the LLM
    """

    counts = report["counts"]

    prompt = f"""
You are an Intelligent Traffic Management Expert.

Analyze the following traffic report.

Location: {location}

Cars: {counts["Car"]}
Motorcycles: {counts["Motorcycle"]}
Buses: {counts["Bus"]}
Trucks: {counts["Truck"]}

Total Vehicles: {report["total"]}

Traffic Density: {report["density"]}

Recommended Signal Time: {report["signal_time"]} seconds

-----------------------------------------

Return the response in VALID MARKDOWN.

Use exactly these headings.

# 🚦 AI Traffic Analysis

## Executive Summary

## Congestion Analysis

## Possible Causes

## Risk Assessment

## Signal Optimization Recommendation

## Traffic Management Recommendations

## Emergency Actions

## Expected Outcome

Rules:

- Use markdown headings.
- Use bullet points wherever appropriate.
- Keep each section concise.
- Do NOT use tables.
- Do NOT use HTML.
- Write professionally.
"""

    return prompt